export enum ErrorResponseTypes {
  BAD_REQUEST = 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  POSTBACK_UNIVERSAL_REQUEST = 'POSTBACK_UNIVERSAL_REQUEST',
}
