export enum IoTModuleStatesEnum {
  INITIALIZING_IN_PROGRESS = 'INITIALIZING_IN_PROGRESS',
  STARTING_IN_PROGRESS = 'STARTING_IN_PROGRESS',
  STOPPING_IN_PROGRESS = 'STOPPING_IN_PROGRESS',
  UPDATING_IN_PROGRESS = 'UPDATING_IN_PROGRESS',
  STARTED = 'STARTED',
  STOPPED = 'STOPPED',
  INITIALIZED = 'INITIALIZED',
  UPDATED = 'UPDATED',
}
