export enum BaseModuleTypeEnum {
  SENSOR = 'SENSOR',
  PUBLISHER = 'PUBLISHER',
}

export enum ModuleTypeEnum {
  BASE = 'BASE',
  CONNECTOR_PROCESSING = 'CONNECTOR_PROCESSING',
  IOT_SENSOR = 'IOT_SENSOR',
  IOT_PUBLISHER = 'IOT_PUBLISHER',
  EDGE_COLLECTOR = 'EDGE_COLLECTOR',
  EDGE_PUBLISHER = 'EDGE_PUBLISHER',
}
