export enum OperationModeEnum {
  CONFIG_MODULE_CREATE_AND_START = 'CONFIG_MODULE_CREATE_AND_START',
  CONFIG_MODULE_CREATE = 'CONFIG_MODULE_CREATE',
  CONFIG_MODULE_REPLACE = 'CONFIG_MODULE_REPLACE',
  START_MODULE = 'START_MODULE',
  STOP_MODULE = 'STOP_MODULE',
  RESTART_MODULE = 'RESTART_MODULE',
  DELETE_MODULE = 'DELETE_MODULE',
  START_ALL = 'START_ALL',
  STOP_ALL = 'STOP_ALL',
  RESTART_ALL = 'RESTART_ALL',
  DELETE_ALL = 'DELETE_ALL',
}
